# -*- coding: utf-8 -*-
"""a1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdN6MLqkdsNd3V-pWDJ-PpmBdJwl8Rkt
"""

print("세개의 정수값을 입력하세여")
n1 = int(input("n1의 정수값을 입력: "))
n2 = int(input("n2의 정수값을 입력: "))
n3 = int(input("n3의 정수값을 입력: "))

total = n1 + n2 + n3
average = total/3 
print(average)